### PR TITLE
fix(input): bdel term buf

### LINKED ISSUE #4606: The prompt terminal buffer still left behind after cancelling prompt input
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001276
node version: v18.14.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: <path>/coc.nvim
term: dumb
platform: darwin

## Log of coc.nvim

2023-04-16T09:52:29.945 INFO (pid:86619) [extension:coc-git] - Looking for git in: git
2023-04-16T09:52:29.969 WARN (pid:86619) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
2023-04-16T09:52:30.096 INFO (pid:86619) [plugin] - coc.nvim initialized with node: v18.14.0 after 282
2023-04-16T09:52:30.108 INFO (pid:86619) [language-client-index] - Language server "cSpell" started with 86625
2023-04-16T09:52:30.907 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 4, 1 ]
2023-04-16T09:52:30.932 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 2 ]
2023-04-16T09:52:30.967 INFO (pid:86619) [configurations] - Add folder configuration from file: /Users/unclebill/github/coc.nvim/.vim/coc-settings.json
2023-04-16T09:52:30.975 INFO (pid:86619) [services] - LanguageClient cssmodules state change: stopped => starting
2023-04-16T09:52:30.980 INFO (pid:86619) [services] - LanguageClient ESLint state change: stopped => starting
2023-04-16T09:52:31.019 INFO (pid:86619) [services] - LanguageClient jsref state change: stopped => starting
2023-04-16T09:52:31.069 INFO (pid:86619) [services] - service tsserver started
2023-04-16T09:52:31.162 INFO (pid:86619) [language-client-index] - Language server "languageserver.cssmodules" started with 86632
2023-04-16T09:52:31.164 INFO (pid:86619) [language-client-index] - Language server "eslint" started with 86635
2023-04-16T09:52:31.166 INFO (pid:86619) [language-client-index] - Language server "jsref" started with 86636
2023-04-16T09:52:31.190 INFO (pid:86619) [core-watchman] - watchman watching project: /Users/unclebill/github/coc.nvim
2023-04-16T09:52:31.221 INFO (pid:86619) [services] - LanguageClient ESLint state change: starting => running
2023-04-16T09:52:31.223 INFO (pid:86619) [services] - service eslint started
2023-04-16T09:52:31.233 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 8 ]
2023-04-16T09:52:31.263 INFO (pid:86619) [services] - LanguageClient cssmodules state change: starting => running
2023-04-16T09:52:31.264 INFO (pid:86619) [services] - service languageserver.cssmodules started
2023-04-16T09:52:31.280 INFO (pid:86619) [services] - LanguageClient jsref state change: starting => running
2023-04-16T09:52:31.280 INFO (pid:86619) [services] - service jsref started
2023-04-16T09:52:31.456 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 7 ]
2023-04-16T09:52:32.639 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 7 ]
2023-04-16T09:52:33.871 INFO (pid:86619) [attach] - receive notification: rename []
2023-04-16T09:52:33.901 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 2 ]
2023-04-16T09:52:33.920 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 8 ]
2023-04-16T09:52:35.113 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 2 ]
2023-04-16T09:52:35.115 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 2 ]
2023-04-16T09:52:35.148 INFO (pid:86619) [attach] - receive notification: doAutocmd [ 8 ]
2023-04-16T09:52:39.791 INFO (pid:86619) [attach] - receive notification: showInfo []


```

## Describe the bug

The terminal buffer created for prompt doesn't get wiped after cancelling the prompt input.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
- Have a extension support `rename` installed, like `coc-tsserver`
- Start vim with command: `vim -u mini.vim`
- Open a typescript file `test.ts`, input `const val = 1`, and move the cursor to `val` variable
- Executing `:call CocActionAsync('rename')`, cancel the prompt after the dialog opens.
- Executing `:ls`, you will a hidden terminal buffer in the list

## Screenshots (optional)

image

### PR DESCRIPTION
**Pull request by fannheyward**
close #4606

### CODE REVIEW

File: src/model/input.ts [hunk 1]
```diff
@@ -160,6 +160,7 @@ export default class InputBox implements Disposable {
     if (this._disposed) return
     this._disposed = true
     this.nvim.call('coc#float#close', [this._winid ?? -1], true)
+    this.nvim.command(`silent! bd! ${this._bufnr}`, true)
```
Comment (UncleBill) [inline src/model/input.ts:163]: Looks good! But I'm wondering that the buffer might get wiped **again** somewhere else. since https://github.com/neoclide/coc.nvim/issues/4606 only happens when you **cancel** the prompt, that means if it got confirmed, the buffer will get wiped properly.

Comment (fannheyward) [reply src/model/input.ts:163]: > if it got confirmed, the buffer will get wiped properly

In my tests, after you confirm the rename prompt, the buffer didn't get wiped. Can you reproduce it?

Comment (UncleBill) [reply src/model/input.ts:163]: > In my tests, after you confirm the rename prompt, the buffer didn't get wiped. Can you reproduce it?

Can't reproduce it. It's OK to me.
